version: 2
updates:
- package-ecosystem: maven
  directory: "/summer-boot-starter-parent"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.springframework.boot:spring-boot-starter-parent
    versions:
    - 2.4.2
    - 2.4.3
  - dependency-name: com.auth0:java-jwt
    versions:
    - 3.12.1
    - 3.13.0
